import { test, expect } from '@playwright/test';
import { faker } from '@faker-js/faker'

test('leave a review with non-select fields empty - error message under all fields: "Obligatory field"', async ({ page }) => {

    test.slow();

    const username = faker.internet.userName();
    const email = username + '@blondmail.com';

    await test.step("register to Inbox", async () => {
        await page.goto('https://inboxes.com/');
        await page.getByRole('button', { name: 'Get my first inbox! arrow right' }).click();
        await page.getByPlaceholder('jane1034').click();

        // Fill username generated by faker
        await page.getByPlaceholder('jane1034').fill(username);
        await page.getByRole('button', { name: 'Add Inbox' }).click();
    })

    await test.step("login to Dzobs", async () => {
        await page.goto('https://www.dzobs.com/');
        await page.getByRole('button', { name: 'Prijava' }).click();
        await page.waitForURL('https://www.dzobs.com/auth/signin?redirect=https://www.dzobs.com/');
        await page.getByPlaceholder('Email').click();

        // Fill email generated by faker
        await page.getByPlaceholder('Email').fill(email);
        await page.getByRole('button', { name: 'Pošalji magični link' }).click();
        await expect(page.getByText('Login link poslan na email')).toBeVisible();
    })

    await test.step("open email received", async () => {
        await page.goto('https://inboxes.com/');
        await page.getByRole('cell', { name: 'Prijavi se na Dzobs.com - [https://i.ibb.co/NWrW3GV/dzobs-logo-...' }).first().click();
        const page1Promise = page.waitForEvent('popup');
        await page.getByRole('link', { name: 'Prijavi se' }).click();
        const page1 = await page1Promise;
        await expect(page1.getByRole('button', { name: 'Odjavi se' })).toBeVisible;
    })

    await test.step("go to companys review fill out form", async () => {
        await page.goto('https://www.dzobs.com/');
        await page.locator('div.relative.group a button span:has-text("Kompanije")').hover();
        await page.getByRole('link', { name: 'Istraži kompanije' }).click();
        await page.getByPlaceholder('Filtriraj po nazivu').click();
        await page.getByPlaceholder('Filtriraj po nazivu').fill('am2');
        await page.getByRole('button', { name: 'Filtriraj' }).click();
        await page.getByRole('link', { name: 'AM2Studio AM2Studio premium' }).click();
        await page.getByRole('link', { name: 'Iskustva' }).click();
        await page.getByRole('button', { name: 'Podjeli svoje iskustvo' }).first().click();
    })

    await test.step("fill out all fields", async () => {
        await page.getByPlaceholder('Software Developer').click();
        await page.getByPlaceholder('Software Developer').fill('Software Developer');
        await page.locator('#react-select-3-placeholder').click();
        await page.getByText('Trenutno radim u kompaniji', { exact: true }).click();
        await page.locator('#react-select-4-placeholder').click();
        await page.getByText('Junior', { exact: true }).click();
        await page.getByText('Select...').click();
        await page.getByText('Manje od godinu dana', { exact: true }).click();
        await page.locator('textarea[name="prosText"]').click();
        await page.locator('textarea[name="prosText"]').fill('pozitivno iskustvo');
        await page.locator('textarea[name="consText"]').click();
        await page.locator('textarea[name="consText"]').fill('negativno iskustvo');
        await page.locator('textarea[name="menadzmentText"]').click();
        await page.locator('textarea[name="menadzmentText"]').fill('poruka za menadzment');
        await page.locator('div').filter({ hasText: /^Plata$/ }).getByRole('button').nth(2).click();
        await page.locator('div').filter({ hasText: /^Lični razvoj$/ }).getByRole('button').nth(2).click();
        await page.locator('div').filter({ hasText: /^Međuljudski odnosi$/ }).getByRole('button').nth(2).click();
        await page.locator('div').filter({ hasText: /^Stručan tim$/ }).getByRole('button').nth(2).click();
        await page.locator('div').filter({ hasText: /^Moderne tehnologije$/ }).getByRole('button').nth(2).click();
        await page.locator('div').filter({ hasText: /^Projekti$/ }).getByRole('button').nth(2).click();
        await page.locator('div').filter({ hasText: /^Privatno\/poslovni život$/ }).getByRole('button').nth(2).click();
        await page.locator('div').filter({ hasText: /^Prilika za napredovanje$/ }).getByRole('button').nth(2).click();
        await page.getByRole('button', { name: 'Pošalji' }).click();
    })

    await test.step("verify review is sent", async () => {
        await expect(page.locator('section').filter({ hasText: 'Hvala!Utisak će biti objavljen kroz par minuta!Idi nazad na kompaniju' }).getByRole('img')).toBeVisible();
    })
});